apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    widebot-task-default: "true"
    service: db
  name: db
spec:
  replicas: 2
  selector:
    matchLabels:
      app: db
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
        - env:
            - name: ACCEPT_EULA
              value: "Y"
            - name: SA_PASSWORD
              value: example_123
          image: mcr.microsoft.com/mssql/server
          livenessProbe:
            exec:
              command:
                - /opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P example_123 -Q 'SELECT 1' || exit 1
            failureThreshold: 10
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 3
          name: db
          ports:
            - containerPort: 1433
---
apiVersion: v1
kind: Service
metadata:
  labels:
    service: db
  name: db
spec:
  ports:
    - name: db
      port: 1433  # Corrected the port to match the container's port
      targetPort: 1433  # Corrected the targetPort to match the container's port
  selector:
    service: db
  type: ClusterIP
